- name: "Verify that required string variables are defined"
  assert:
    that: 
      - required_variable is defined
      - required_variable | length > 0
      - required_variable != None
    fail_msg: "{{ required_variable }} needs to be set for the role to work"
    success_msg: "Required variable {{ required_variable}} is defined"
  loop_control:
    loop_var: required_variable
  with_items:
    - "{{ LB_ID }}"
    - "{{ LB_PUBLIC_IP }}"
    - "{{ KONG_HOSTNAME }}"
  no_log: True
  

## Kong

- name: Creating kong.yaml
  template:
    src: kong.j2
    dest: kong.yaml

- name: Setup Harness
  shell: kubectl apply -f kong.yaml

- name: Deleting kong.yaml
  file:
    path: kong.yaml
    state: absent